name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests Jest
        run: npx jest --coverage
      
      - name: Installer Playwright
        run: npx playwright install --with-deps

      - name: Lancer les tests E2E (Playwright)
        run: npx playwright test

